## What are NumPy and NumPy arrays?

### NumPy arrays

**Python** objects  

> -   high-level number objects: integers, floating point
> -   containers: lists (costless insertion and append), dictionaries
>     (fast lookup)

**NumPy** provides  

> -   extension package to Python for multi-dimensional arrays
> -   closer to hardware (efficiency)
> -   designed for scientific computation (convenience)
> -   Also known as *array oriented computing*

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

For example, An array containing:

-   values of an experiment/simulation at discrete time steps
-   signal recorded by a measurement device, e.g. sound wave
-   pixels of an image, grey-level or colour
-   3-D data measured at different X-Y-Z positions, e.g. MRI scan
-   ...

**Why it is useful:** Memory-efficient container that provides fast
numerical operations.

In [4]:
In [1]: L = range(1000)

In [2]: %timeit [i**2 for i in L]
# 1000 loops, best of 3: 403 us per loop

In [3]: a = np.arange(1000)

In [4]: %timeit a**2
# 100000 loops, best of 3: 12.7 us per loop

564 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.65 µs ± 523 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
    In [5]: np.array?
#     String Form:<built-in function array>
#     Docstring:
#     array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0, ...

### Import conventions

The recommended convention to import numpy is:

In [5]:
import numpy as np

## Creating arrays

### Manual construction of arrays

-   **1-D**:

In [7]:
    a = np.array([0, 1, 2, 3])
    a

array([0, 1, 2, 3])

In [8]:
    a.ndim

1

In [9]:
    a.shape

(4,)

In [10]:
    len(a)

4

-   **2-D, 3-D, ...**:

In [11]:
    b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
    b

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
    b.ndim

2

In [13]:
    b.shape

(2, 3)

In [14]:
    len(b)     # returns the size of the first dimension

2

In [15]:
    c = np.array([[[1], [2]], [[3], [4]]])
    c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [16]:
    c.shape

(2, 2, 1)

### Functions for creating arrays

Tip

In practice, we rarely enter items one by one...

-   Evenly spaced:

In [17]:
    a = np.arange(10) # 0 .. n-1  (!)
    a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
    b = np.arange(1, 9, 2) # start, end (exclusive), step
    b

array([1, 3, 5, 7])

-   or by number of points:

In [19]:
    c = np.linspace(0, 1, 6)   # start, end, num-points
    c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [20]:
    d = np.linspace(0, 1, 5, endpoint=False)
    d

array([0. , 0.2, 0.4, 0.6, 0.8])

-   Common arrays:

In [21]:
    a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
    a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
    b = np.zeros((2, 2))
    b

array([[0., 0.],
       [0., 0.]])

In [23]:
    c = np.eye(3)
    c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
    d = np.diag(np.array([1, 2, 3, 4]))
    d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

-   `np.random` : random numbers (Mersenne Twister PRNG):

In [27]:
    a = np.random.rand(10)       # uniform in [0, 1]
    a  # doctest: +SKIP

array([0.70680807, 0.56166296, 0.93077022, 0.61919016, 0.01349828,
       0.21723808, 0.94519723, 0.36301484, 0.78342938, 0.17060734])

In [31]:
    b = np.random.randn(4)      # Gaussian
    b  # doctest: +SKIP

array([ 0.53293762, -2.54983019,  0.41966464,  0.7288669 ])

In [32]:
    np.random.seed(1234)        # Setting the random seed

## Basic data types

You may have noticed that, in some instances, array elements are
displayed with a trailing dot (e.g. `2.` vs `2`). This is due to a
difference in the data-type used:

In [33]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [34]:
b = np.array([1., 2., 3.])
b.dtype

dtype('float64')

Tip

Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers. Note
that, in the example above, NumPy auto-detects the data-type from the
input.

------------------------------------------------------------------------

You can explicitly specify which data-type you want:

In [35]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

dtype('float64')

The **default** data type is floating point:

In [36]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

There are also other types:

Complex  

In [37]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

dtype('complex128')

There are also other types:

Complex  

In [38]:
e = np.array([True, False, False, True])
e.dtype

dtype('bool')

In [41]:
f = np.array(['Bonjour', 'Hello', 'Hallo'])
f.dtype 

dtype('<U7')

Much more  

> -   `int32`
> -   `int64`
> -   `uint32`
> -   `uint64`

## Indexing and slicing

The items of an array can be accessed and assigned to the same way as
other Python sequences (e.g. lists):

In [42]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[0], a[2], a[-1]

(0, 2, 9)

The usual python idiom for reversing a sequence is supported:

In [44]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

For multidimensional arrays, indexes are tuples of integers:

In [45]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [46]:
a[1, 1]

1

In [47]:
a[2, 1] = 10 # third line, second column
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [48]:
a[1]

array([0, 1, 0])

Note

-   In 2D, the first dimension corresponds to **rows**, the second to
    **columns**.
-   for multidimensional `a`, `a[0]` is interpreted by taking all
    elements in the unspecified dimensions.

**Slicing**: Arrays, like other Python sequences can also be sliced:

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[2:9:3] # [start:end:step]

array([2, 5, 8])

Note that the last index is not included! :

In [51]:
a[:4]

array([0, 1, 2, 3])

All three slice components are not required: by default, $start$ is 0,
$end$ is the last and $step$ is 1:

In [52]:
a[1:3]

array([1, 2])

In [53]:
a[::2]

array([0, 2, 4, 6, 8])

In [54]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

A small illustrated summary of NumPy indexing and slicing...


<img src="images/numpy_indexing.png" class="align-center" style="width:70.0%" alt="image" />

You can also combine assignment and slicing:

In [55]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [56]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## Copies and views

A slicing operation creates a **view** on the original array, which is
just a way of accessing array data. Thus the original array is not
copied in memory. You can use `np.may_share_memory()` to check if two
arrays share the same memory block. Note however, that this uses
heuristics and may give you false positives.

**When modifying the view, the original array is modified as well**:

In [57]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [59]:
np.may_share_memory(a, b)

True

In [60]:
b[0] = 12
b

array([12,  2,  4,  6,  8])

In [61]:
a   # (!)

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [62]:
a = np.arange(10)
c = a[::2].copy()  # force a copy
c[0] = 12
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.may_share_memory(a, c)

False

## Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean or
integer arrays (**masks**). This method is called *fancy indexing*. It
creates **copies not views**.

### Using boolean masks

In [64]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [65]:
(a % 3 == 0)

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [66]:
mask = (a % 3 == 0)
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a           # extract a sub-array with the mask

array([ 3,  0,  9,  6,  0, 12])

Indexing with a mask can be very useful to assign a new value to a
sub-array:

In [67]:
a[a % 3 == 0] = -1
a

array([10, -1,  8, -1, 19, 10, 11, -1, 10, -1, -1, 20, -1,  7, 14])

### Indexing with an array of integers

In [68]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Indexing can be done with an array of integers, where the same index is
repeated several time:

In [69]:
a[[2, 3, 2, 4, 2]]  # note: [2, 3, 2, 4, 2] is a Python list

array([20, 30, 20, 40, 20])

New values can be assigned with this kind of indexing:

In [70]:
a[[9, 7]] = -100
a

array([   0,   10,   20,   30,   40,   50,   60, -100,   80, -100])

Tip

When a new array is created by indexing with an array of integers, the
new array has the same shape as the array of integers:

In [71]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape

(2, 2)

In [72]:
a[idx]

array([[3, 4],
       [9, 7]])

The image below illustrates various fancy indexing applications

<img src="images/numpy_fancy_indexing.png" class="align-center" style="width:80.0%" alt="image" />


# Numerical operations on arrays

### Basic operations

With scalars:

In [73]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [74]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

All arithmetic operates elementwise:

In [75]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [76]:
a * b

array([2., 4., 6., 8.])

In [77]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

These operations are of course much faster than if you did them in pure
python:

In [78]:
a = np.arange(10000)
%timeit a + 1  # doctest: +SKIP

10.3 µs ± 965 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [79]:
l = range(10000)
%timeit [i+1 for i in l] # doctest: +SKIP

924 µs ± 19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Warning

**Array multiplication is not matrix multiplication:**

In [80]:
c = np.ones((3, 3))
c * c                   # NOT matrix multiplication!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Note

**Matrix multiplication:**

In [81]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### Other operations

**Comparisons:**

In [82]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [83]:
a > b

array([False, False,  True, False])

Tip

Array-wise comparisons:

In [84]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
np.array_equal(a, b)

False

In [85]:
np.array_equal(a, c)

True

**Logical operations:**

In [86]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [87]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental functions:**

In [88]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.log(a)

C:\Users\bhumik\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [90]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape mismatches**

In [91]:
a = np.arange(4)
a + np.array([1, 2])  # doctest: +SKIP

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

*Broadcasting?* We'll return to that [later](broadcasting.ipynb).

**Transposition:**

In [92]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [93]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

Warning

**The transposition is a view**

As a result, the following code **is wrong** and will **not make a
matrix symmetric**:

In [94]:
a += a.T

It will work for small arrays (because of buffering) but fail for large
one, in unpredictable ways.

Note

**Linear algebra**

The sub-module `numpy.linalg` implements basic linear algebra, such as
solving linear systems, singular value decomposition, etc. However, it
is not guaranteed to be compiled using efficient routines, and thus we
recommend the use of `scipy.linalg`, as detailed in section
[scipy\_linalg](scipy_linalg.ipynb)

## Basic reductions

### Computing sums

In [95]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [96]:
x.sum()

10

<img src="images/reductions.png" class="align-right" alt="image" />

Sum by rows and by columns:

In [97]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [98]:
x.sum(axis=0)   # columns (first dimension)

array([3, 3])

In [99]:
x[:, 0].sum(), x[:, 1].sum()

(3, 3)

In [100]:
x.sum(axis=1)   # rows (second dimension)

array([2, 4])

In [101]:
x[0, :].sum(), x[1, :].sum()

(2, 4)

Tip

Same idea in higher dimensions:

In [102]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]     # doctest: +ELLIPSIS

1.2671177193964822

In [103]:
x[0, 1, :].sum()     # doctest: +ELLIPSIS

1.2671177193964822

### Other reductions

--- works the same way (and take `axis=`)

**Extrema:**

In [104]:
x = np.array([1, 3, 2])
x.min()

1

In [105]:
x.max()

3

In [106]:
x.argmin()  # index of minimum

0

In [107]:
x.argmax()  # index of maximum

1

**Logical operations:**

In [108]:
np.all([True, True, False])

False

In [109]:
np.any([True, True, False])

True

Note

Can be used for array comparisons:

In [110]:
a = np.zeros((100, 100))
np.any(a != 0)

False

In [111]:
np.all(a == a)

True

In [112]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

**Statistics:**

In [113]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [114]:
np.median(x)

1.5

In [115]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [116]:
x.std()          # full population standard dev.

0.82915619758885

... and many more (best to learn as you go).